feat(sms): Add SMS plugin
Vonage/vonage-cli pull request #49
Opened 2022-02-03 00:06 UTC by kellyjandrews

This PR adds the plugin for sending SMS with the CLI.

In order to test, have a working local copy of the cli, and use `bin/run plugins:link ./packages/sms` and run tests with `npx lerna run test --scope=`@vonage/cli-plugin-sms`

2022-02-04 14:56 UTC, amdcavallaro commented on packages/sms/src/commands/sms/index.ts
> +import { flags, OutputFlags } from '@oclif/parser';;
```suggestion
import { flags, OutputFlags } from '@oclif/parser';
```

2022-02-04 14:57 UTC, amdcavallaro commented on packages/sms/src/commands/sms/index.ts
> +import { request } from '@vonage/vetch'
Hey @kellyjandrews I notice some lines end in ; others not. Maybe keep it consistent across the files?
```suggestion
import { request } from '@vonage/vetch';
```

2022-02-04 14:58 UTC, kellyjandrews commented on packages/sms/src/commands/sms/index.ts
> +import { request } from '@vonage/vetch'
Need to get eslint set up properly so it will keep it consistent, yes.

2022-02-04 15:48 UTC, matt-lethargic approved these changes

2022-02-08 13:54 UTC, pardel requested changes

2022-02-08 13:54 UTC, pardel commented on packages/sms/src/commands/sms/index.ts
> +    `vonage sms --to=5551234567 --from=5551234567 --message="Hello there!`,
number format used in example is invalid

2022-02-08 13:54 UTC, pardel commented on packages/sms/package.json
> +        "oclif-plugin"
can we add Vonage, CLI & this plugin specific keywords?

2022-02-10 20:36 UTC, pardel requested changes
sorry, would like to request some changes

2022-02-10 22:20 UTC, pardel requested changes

2022-02-10 22:20 UTC, pardel commented on packages/sms/README.md
> +@vonage/cli-plugin-numbers
Seems like the wrong info here

2022-02-10 22:20 UTC, pardel commented on packages/sms/oclif.manifest.json
> +{"version":"1.1.0","commands":{"sms":{"id":"sms","description":"","pluginName":"@vonage/cli-plugin-numbers","pluginType":"core","aliases":[],"examples":["vonage sms"],"flags":{"help":{"name":"help","
pluginName is wrong here

2022-02-10 22:20 UTC, pardel commented on packages/sms/src/commands/sms/index.ts
> +    `vonage sms --to=15551234567 --from=15551234567 --message="Hello there!`,
There is a missing quote at the end of the example - we should also used single-quotes. The double don't work on the macOS default terminal

2022-02-10 22:20 UTC, pardel commented on packages/sms/oclif.manifest.json
> +{"version":"1.1.0","commands":{"sms":{"id":"sms","description":"","pluginName":"@vonage/cli-plugin-numbers","pluginType":"core","aliases":[],"examples":["vonage sms"],"flags":{"help":{"name":"help","
The help command doesn't seem to be implemented with an example:
<img width="436" alt="Screenshot 2022-02-10 at 22 10 39" src="https://user-images.githubusercontent.com/2171/153506366-e0320fb3-39db-40a1-9e9f-b4a9bafcafb7.png">

2022-02-11 15:19 UTC, kellyjandrews commented on packages/sms/src/commands/sms/index.ts
> +    `vonage sms --to=15551234567 --from=15551234567 --message="Hello there!`,
Good catch - thanks! I'll update that this afternoon.

2022-02-11 15:20 UTC, kellyjandrews commented on packages/sms/oclif.manifest.json
> +{"version":"1.1.0","commands":{"sms":{"id":"sms","description":"","pluginName":"@vonage/cli-plugin-numbers","pluginType":"core","aliases":[],"examples":["vonage sms"],"flags":{"help":{"name":"help","
Right - this I need to investigate - see https://jira.vonage.com/browse/DEVX-5881

Seems to only be the SMS plugin, so not exactly sure what I've missed.

2022-02-11 15:21 UTC, kellyjandrews commented on packages/sms/README.md
> +@vonage/cli-plugin-numbers
🤦🏻‍♂️ thanks - definitely need to change that

2022-02-18 14:29 UTC, abdulajet approved these changes
lgtm

2022-02-22 00:00 UTC, kellyjandrews commented
@pardel Can you also approve - I'd like to get these changes published. Thanks!

2022-02-22 15:25 UTC, merged